platform :ios, '8.0'
use_frameworks!

def testing_pods
   pod "HeapInspector", :path => "../../HeapInspector.podspec"
end
 
target 'HeapInspectorExample' do
    testing_pods
end
 
target 'HeapInspectorExampleTests' do
    testing_pods
end

target 'SwiftExample' do
    testing_pods
end
 
target 'SwiftExampleTests' do
    testing_pods
end

